---
services:
  traefik:
    image: "traefik:latest"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./configs/:/etc/traefik/dynamic/:ro
      - ./data/certs/:/var/traefik/certs/:rw
    networks:
      - traefik
networks:
  traefik:
    external: false